//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class creditnoteitem
    {
        public int id { get; set; }
        public Nullable<int> date { get; set; }
        public string name { get; set; }
        public decimal unitrate { get; set; }
        public decimal unitdiscount { get; set; }
        public decimal unittaxable { get; set; }
        public decimal qty { get; set; }
        public decimal nettotal { get; set; }
        public Nullable<int> item_id { get; set; }
        public Nullable<int> admin_id { get; set; }
        public System.DateTime updated_at { get; set; }
        public System.DateTime created_at { get; set; }
        public Nullable<int> sync_id { get; set; }
        public int creditnote_id { get; set; }
    
        public virtual admin admin { get; set; }
        public virtual item item { get; set; }
    }
}
