//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class creditnote
    {
        public int id { get; set; }
        public string fiscal_year { get; set; }
        public int creditnote_no { get; set; }
        public string customer_name { get; set; }
        public string customer_address { get; set; }
        public string customer_phone { get; set; }
        public string customer_PAN { get; set; }
        public string bill_date { get; set; }
        public decimal amount { get; set; }
        public Nullable<int> bill_id { get; set; }
        public Nullable<int> admin_id { get; set; }
        public Nullable<int> date { get; set; }
        public int reprintamount { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
        public Nullable<int> sync_id { get; set; }
        public Nullable<int> customer_id { get; set; }
    
        public virtual admin admin { get; set; }
        public virtual bill bill { get; set; }
        public virtual customer customer { get; set; }
    }
}
