//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public item()
        {
            this.billitems = new HashSet<billitem>();
            this.creditnoteitems = new HashSet<creditnoteitem>();
            this.supplyitems = new HashSet<supplyitem>();
            this.variances = new HashSet<variance>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> category_id { get; set; }
        public string pic { get; set; }
        public Nullable<System.DateTime> exps { get; set; }
        public string Discription { get; set; }
        public Nullable<int> sync_id { get; set; }
        public Nullable<System.DateTime> lastsync { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<decimal> stock { get; set; }
        public Nullable<decimal> rate { get; set; }
        public string itemcode { get; set; }
        public string barcode { get; set; }
        public Nullable<decimal> buyrate { get; set; }
        public Nullable<decimal> wholesaleprice { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<billitem> billitems { get; set; }
        public virtual category category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<creditnoteitem> creditnoteitems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<supplyitem> supplyitems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<variance> variances { get; set; }
    }
}
