//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public payment()
        {
            this.customerpaids = new HashSet<customerpaid>();
            this.supplierpaids = new HashSet<supplierpaid>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> dates { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<int> type { get; set; }
        public string bank { get; set; }
        public string accno { get; set; }
        public string voucher_no { get; set; }
        public string cheque_no { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<customerpaid> customerpaids { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<supplierpaid> supplierpaids { get; set; }
    }
}
