//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class salary
    {
        public int id { get; set; }
        public Nullable<int> employee_id { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<System.DateTime> form { get; set; }
        public Nullable<System.DateTime> toto { get; set; }
        public Nullable<System.DateTime> dates { get; set; }
        public Nullable<int> sync_id { get; set; }
        public Nullable<System.DateTime> lastsync { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<int> month { get; set; }
        public Nullable<int> day { get; set; }
        public Nullable<int> today { get; set; }
        public Nullable<int> tomonth { get; set; }
        public Nullable<int> toyear { get; set; }
    
        public virtual employee employee { get; set; }
    }
}
