//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplierpaid
    {
        public int id { get; set; }
        public Nullable<System.DateTime> paiddate { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<int> supplier_id { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<int> month { get; set; }
        public Nullable<int> day { get; set; }
        public Nullable<int> payment_id { get; set; }
        public Nullable<int> ficiak_id { get; set; }
        public Nullable<int> ficialyear_id { get; set; }
    
        public virtual ficialyear ficialyear { get; set; }
        public virtual ficialyear ficialyear1 { get; set; }
        public virtual payment payment { get; set; }
        public virtual vendor vendor { get; set; }
    }
}
