//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vendor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vendor()
        {
            this.supplieradvances = new HashSet<supplieradvance>();
            this.supplierpaids = new HashSet<supplierpaid>();
            this.supplies = new HashSet<supply>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string adress { get; set; }
        public string phoneno { get; set; }
        public string email { get; set; }
        public Nullable<decimal> due { get; set; }
        public Nullable<decimal> advance { get; set; }
        public string panno { get; set; }
        public string vatno { get; set; }
        public Nullable<int> sync_id { get; set; }
        public Nullable<System.DateTime> lastsync { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<supplieradvance> supplieradvances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<supplierpaid> supplierpaids { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<supply> supplies { get; set; }
    }
}
